services:
  app:
    image: customers_api:latest
    depends_on:
      mysqlDb:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=mysqlDb
  mysqlDb:
    image: mysql:8.4
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: customers
        MYSQL_USER: customer
        MYSQL_PASSWORD: customer
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 1
    expose:
      - 3306